"""Add google_id to user

Revision ID: efc5ccbb4daf
Revises: e4fa9fc8e44a
Create Date: 2023-12-27 01:51:13.805199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc5ccbb4daf'
down_revision: Union[str, None] = 'e4fa9fc8e44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
